### ISSUE TITLE
creating time tracker page by timestamps

### ISSUE THREAD

**Issue by sivagurubilli** [sivagurubilli/equable-pleasure-9638#10]

**Comment by sivagurubilli** [comment]
- [x] build the task taking box
- [x] build the input in task taking box and buttons
- [x] build the set up of redux for time stamps
- [x] for making reducer in redux for timestaps for particular task
- [x] taking start time and time and make difference and add it to the task time
- [x] dispalying the total time in difference places
- [x] making backend to the task and assign timestaps
- [x] make  set up for backend 
- [x] make models and routes for time for tasks
- [x] make data base ready for taksand projects seperately
